# Bibioteca NumPy (Créditos ao Professor Luciano Nunes)

A primeira tarefa a ser efetuada é importar a biblioteca NumPy. É muito comum criar um alias para o import, facilitando sua utilização.

Note que o Anaconda já cuidou da instalação da biblioteca NumPy. Caso a execução

In [1]:
import numpy as np

## Criando arrays a partir de listas

In [9]:
lista = [1, 2, 3]

In [10]:
lista

[1, 2, 3]

In [18]:
np.array(lista)

array([1, 2, 3])

## Criando matrizes a partir de listas

In [15]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [16]:
matriz

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [49]:
np.array(matriz)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Principais Métodos da NumPy

### Método: **arange()**
Semelhante ao range do Python, porém devolve um array com os elementos que estão dentro do intervalo selecionado.

*Dica: ao digitar o nome do método, o comando shift+tab mostra a documentação!*

In [19]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [21]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

### Método: zeros()

Retorna uma matriz com a dimensão informada, preenchido com zeros.

In [27]:
np.zeros(3)

array([0., 0., 0.])

O tipo padrão é float, porém pode ser alterado pelo parâmetro **dtype**

In [26]:
np.zeros(3, dtype=int)

array([0, 0, 0])

Para uma matriz com mais de uma dimensão, o parâmetro com as dimensões deverá ser uma tupla.

In [25]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [28]:
np.zeros((3, 3, 3), dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

### Método: ones()

Da mesma forma do método *zeros()*, retorna uma matriz com a dimensão informada, preenchida com 1.

In [29]:
np.ones(3)

array([1., 1., 1., 1.])

In [30]:
np.ones(3, dtype=int)

array([1, 1, 1])

In [37]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

### Método: linspace()

Cria uma sequencia de números igualmente espaçados entre os limites dados.

In [33]:
np.linspace(0, 50, 5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [41]:
np.linspace(0, 100, 10, dtype=int)

array([  0,  11,  22,  33,  44,  55,  66,  77,  88, 100])

### Método: eye()

Retorna a **matriz identidade** com a dimensão informada.

In [46]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

## Sub-biblioteca random

Sub-biblioteca do NumPy com diversos métodos para geração de números aleatórios.

### Método: rand()

Retorna uma matriz com a dimensão informada, preenchidas com números aleatórios de 0 a 1 seguindo uma distribuição uniforme (probabilidade).

In [50]:
np.random.rand(5)

array([0.15129555, 0.14768435, 0.03281802, 0.53032531, 0.3050079 ])

In [51]:
np.random.rand(5, 3)

array([[0.09408305, 0.5844936 , 0.24053192],
       [0.1031776 , 0.04669607, 0.39223218],
       [0.54798497, 0.11736657, 0.37006432],
       [0.55027436, 0.29153793, 0.0416521 ],
       [0.24699954, 0.45108236, 0.25925499]])

É possível incluir operações na criação de números aleatórios

In [52]:
np.random.rand(5) * 100

array([35.72221858,  7.11335604, 62.45747769,  2.12625336, 18.4276964 ])

In [53]:
np.random.rand(3, 3) * 10

array([[6.75228754, 4.10166417, 6.48199052],
       [8.48188063, 9.28646231, 0.20593596],
       [8.44380881, 7.88633667, 0.83518453]])

### Método: randn()

Retorna uma matriz com a dimensão informada, preenchida com números aleatórios, seguindo uma distribuição normal.

In [54]:
np.random.randn(5)

array([ 1.6315143 , -1.05233555, -0.8083312 ,  0.03853841,  0.75398263])

In [55]:
np.random.randn(3, 4)

array([[ 0.47533537,  1.28618905, -0.43912208,  0.27683721],
       [-0.42700631, -0.97715179,  1.77204979,  0.46947665],
       [-0.69425612,  1.94739085, -0.16814517,  0.12131888]])

In [56]:
np.random.randn(5) * 100

array([  75.12317553,   80.3188204 ,  -20.3371063 , -127.68228453,
       -217.37587859])

### Método: randint()

Retorna um número inteiro aleatório entre o intervalo informado ou uma matriz unidimensional, preenchida com números aleatórios inteiros, entre o intervalo informado.

In [59]:
np.random.randint(1, 10)

6

In [61]:
np.random.randint(1, 100, 15)

array([ 2, 84, 23, 81, 93, 65, 26, 68, 58, 19, 34, 23, 93,  6, 13])

## Métodos e atributos do objeto NymPy Array

### Método: reshape()

Reorganiza um array em uma dimensão diferente da original.

In [67]:
myarray = np.random.rand(10)

In [68]:
myarray

array([0.91331819, 0.37747315, 0.97134596, 0.17159074, 0.52739367,
       0.3971721 , 0.11486857, 0.90691767, 0.69858945, 0.55677237])

In [70]:
myarray.reshape(2, 5)

array([[0.91331819, 0.37747315, 0.97134596, 0.17159074, 0.52739367],
       [0.3971721 , 0.11486857, 0.90691767, 0.69858945, 0.55677237]])

In [71]:
myarray.reshape(5, 2)

array([[0.91331819, 0.37747315],
       [0.97134596, 0.17159074],
       [0.52739367, 0.3971721 ],
       [0.11486857, 0.90691767],
       [0.69858945, 0.55677237]])

In [75]:
myarray.reshape(2, 5).reshape(10)

array([0.91331819, 0.37747315, 0.97134596, 0.17159074, 0.52739367,
       0.3971721 , 0.11486857, 0.90691767, 0.69858945, 0.55677237])

### Método: max()

Retorna o maior valor dentro de um array.

In [76]:
myarray.max()

0.97134596316619

### Método: argmax()

Retorna o índice do maior valor dentro de um array.

In [104]:
myarray.argmax()

2

In [105]:
myarray[2]

0.97134596316619

### Método: min()

Retorna o menor valor dentro de um array.

In [77]:
myarray.min()

0.11486856967275094

### Método: argmin()

Retorna o índice do menor valor dentro de um array.

In [80]:
myarray.argmin()

6

In [106]:
myarray[6]

0.11486856967275094

### Atributo: shape

Retorna o formado do array.

In [74]:
myarray.shape

(10,)

In [97]:
a = np.random.rand(3, 4)

In [98]:
a

array([[0.54676706, 0.39643651, 0.12234473, 0.0320983 ],
       [0.43777012, 0.5997014 , 0.19956206, 0.44057975],
       [0.06871029, 0.1962494 , 0.68245538, 0.8314667 ]])

In [99]:
a.shape

(3, 4)

In [100]:
a = a.reshape(2, 6)

In [101]:
a

array([[0.54676706, 0.39643651, 0.12234473, 0.0320983 , 0.43777012,
        0.5997014 ],
       [0.19956206, 0.44057975, 0.06871029, 0.1962494 , 0.68245538,
        0.8314667 ]])

In [107]:
a.shape

(2, 6)

## Mais métodos do objeto NymPy Array

### Método: mean()
Retorna a média aritmética simples dos elementos do array

In [12]:
a = np.array([1, 2, 3, 4])

In [11]:
a.mean()

2.5

In [13]:
a = np.array([[[1, 2], [3, 4], [5, 6]]])

In [14]:
a.mean()

3.5

### Método: std()
Retorna o desvio padrão

In [12]:
a = np.array([1, 2, 3, 4])

In [99]:
a.std()

1.707825127659933

In [104]:
a = np.array([[[1, 2], [3, 4], [99, 777]]])

In [105]:
a.std()

283.64512256613114

### Método: sum()

In [106]:
a = np.array([1, 2, 3, 4])

In [107]:
a.sum()

10

In [114]:
a = np.array([[[1, 2], [3, 4], [99, 777]]])
a

array([[[  1,   2],
        [  3,   4],
        [ 99, 777]]])

In [109]:
a.sum()

886

In [113]:
a.sum(axis=1)

array([[103, 783]])

In [112]:
a.sum(axis=2)

array([[  3,   7, 876]])

## Inserindo e excluindo elementos

### Inserindo elementos de um array unidimensional

In [93]:
arr = np.array([1, 2, 3, 5, 6, 7, 8])
arr

array([1, 2, 3, 5, 6, 7, 8])

In [94]:
np.insert(arr, 3, 4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [96]:
np.insert(arr, 3, [99, 98, 88, 55])

array([ 1,  2,  3, 99, 98, 88, 55,  5,  6,  7,  8])

In [98]:
np.insert(arr, (3, 6), [88, 55])

array([ 1,  2,  3, 88,  5,  6,  7, 55,  8])

### Inserindo elementos de um array bidimensional

In [120]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [121]:
np.insert(arr, [1], [[6],[9],], axis = 0)

array([[ 0,  1,  2,  3],
       [ 6,  6,  6,  6],
       [ 9,  9,  9,  9],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [122]:
np.insert(arr, [1], [[8],[7],[9]], axis = 1)

array([[ 0,  8,  1,  2,  3],
       [ 4,  7,  5,  6,  7],
       [ 8,  9,  9, 10, 11]])

In [124]:
arr = np.arange(6).reshape(2, 3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [125]:
np.insert(arr, (2, 4), 9)

array([0, 1, 9, 2, 3, 9, 4, 5])

In [128]:
arr = np.arange(12).reshape(3, 4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [129]:
np.insert(arr, (0, 3), 66, axis = 1)

array([[66,  0,  1,  2, 66,  3],
       [66,  4,  5,  6, 66,  7],
       [66,  8,  9, 10, 66, 11]])

### Excluindo elementos de um array unidimensional

In [132]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [133]:
np.delete(arr, 3)

array([1, 2, 3, 5, 6, 7, 8])

In [134]:
np.delete(arr, np.s_[2:4])

array([1, 2, 5, 6, 7, 8])

### Excluindo elementos de um array bidimensional

In [138]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [139]:
np.delete(arr, 2, 1)

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12]])

In [140]:
np.delete(arr, 1, 0)

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [141]:
np.delete(arr, np.s_[1:], 0)

array([[1, 2, 3, 4]])

In [142]:
np.delete(arr, np.s_[1:3], 1)

array([[ 1,  4],
       [ 5,  8],
       [ 9, 12]])

In [143]:
np.delete(arr, 1, None)

array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## Funções Universais da NumPy

Também conhecidas por UFUNC são diversas funções que operam sobre NumPy Arrays em forma de **broadcasting** (transmissão), ou seja, a NumPy irá iterar no array executando a função determinada em cada elemento.

### Funções Matemáticas:

|Função|Descrição
|---|---|
add(x1, x2, /[, out, where, casting, order, …])|Add arguments element-wise.
subtract(x1, x2, /[, out, where, casting, …])|Subtract arguments, element-wise.
multiply(x1, x2, /[, out, where, casting, …])|Multiply arguments element-wise.
divide(x1, x2, /[, out, where, casting, …])|Returns a true division of the inputs, element-wise.
logaddexp(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs.
logaddexp2(x1, x2, /[, out, where, casting, …])|Logarithm of the sum of exponentiations of the inputs in base-2.
true_divide(x1, x2, /[, out, where, …])|Returns a true division of the inputs, element-wise.
floor_divide(x1, x2, /[, out, where, …])|Return the largest integer smaller or equal to the division of the inputs.
negative(x, /[, out, where, casting, order, …])|Numerical negative, element-wise.
positive(x, /[, out, where, casting, order, …])|Numerical positive, element-wise.
power(x1, x2, /[, out, where, casting, …])|First array elements raised to powers from second array, element-wise.
remainder(x1, x2, /[, out, where, casting, …])|Return element-wise remainder of division.
mod(x1, x2, /[, out, where, casting, order, …])|Return element-wise remainder of division.
fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.
divmod(x1, x2[, out1, out2], / [[, out, …])|Return element-wise quotient and remainder simultaneously.
absolute(x, /[, out, where, casting, order, …])|Calculate the absolute value element-wise.
fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.
rint(x, /[, out, where, casting, order, …])|Round elements of the array to the nearest integer.
sign(x, /[, out, where, casting, order, …])|Returns an element-wise indication of the sign of a number.
heaviside(x1, x2, /[, out, where, casting, …])|Compute the Heaviside step function.
conj(x, /[, out, where, casting, order, …])|Return the complex conjugate, element-wise.
exp(x, /[, out, where, casting, order, …])|Calculate the exponential of all elements in the input array.
exp2(x, /[, out, where, casting, order, …])|Calculate 2**p for all p in the input array.
log(x, /[, out, where, casting, order, …])|Natural logarithm, element-wise.
log2(x, /[, out, where, casting, order, …])|Base-2 logarithm of x.
log10(x, /[, out, where, casting, order, …])|Return the base 10 logarithm of the input array, element-wise.
expm1(x, /[, out, where, casting, order, …])|Calculate exp(x) - 1 for all elements in the array.
log1p(x, /[, out, where, casting, order, …])|Return the natural logarithm of one plus the input array, element-wise.
sqrt(x, /[, out, where, casting, order, …])|Return the non-negative square-root of an array, element-wise.
square(x, /[, out, where, casting, order, …])|Return the element-wise square of the input.
cbrt(x, /[, out, where, casting, order, …])|Return the cube-root of an array, element-wise.
reciprocal(x, /[, out, where, casting, …])|Return the reciprocal of the argument, element-wise.
gcd(x1, x2, /[, out, where, casting, order, …])|Returns the greatest common divisor of |x1| and |x2|
lcm(x1, x2, /[, out, where, casting, order, …])|Returns the lowest common multiple of |x1| and |x2|


### Funções Trigonométricas:

|Função|Descrição
|---|---|
sin(x, /[, out, where, casting, order, …])|Trigonometric sine, element-wise.
cos(x, /[, out, where, casting, order, …])|Cosine element-wise.
tan(x, /[, out, where, casting, order, …])|Compute tangent element-wise.
arcsin(x, /[, out, where, casting, order, …])|Inverse sine, element-wise.
arccos(x, /[, out, where, casting, order, …])|Trigonometric inverse cosine, element-wise.
arctan(x, /[, out, where, casting, order, …])|Trigonometric inverse tangent, element-wise.
arctan2(x1, x2, /[, out, where, casting, …])|Element-wise arc tangent of x1/x2 choosing the quadrant correctly.
hypot(x1, x2, /[, out, where, casting, …])|Given the “legs” of a right triangle, return its hypotenuse.
sinh(x, /[, out, where, casting, order, …])|Hyperbolic sine, element-wise.
cosh(x, /[, out, where, casting, order, …])|Hyperbolic cosine, element-wise.
tanh(x, /[, out, where, casting, order, …])|Compute hyperbolic tangent element-wise.
arcsinh(x, /[, out, where, casting, order, …])|Inverse hyperbolic sine element-wise.
arccosh(x, /[, out, where, casting, order, …])|Inverse hyperbolic cosine, element-wise.
arctanh(x, /[, out, where, casting, order, …])|Inverse hyperbolic tangent element-wise.
deg2rad(x, /[, out, where, casting, order, …])|Convert angles from degrees to radians.
rad2deg(x, /[, out, where, casting, order, …])|Convert angles from radians to degrees.

### Funções Binárias:

|Função|Descrição
|---|---|
bitwise_and(x1, x2, /[, out, where, …])|Compute the bit-wise AND of two arrays element-wise.
bitwise_or(x1, x2, /[, out, where, casting, …])|Compute the bit-wise OR of two arrays element-wise.
bitwise_xor(x1, x2, /[, out, where, …])|Compute the bit-wise XOR of two arrays element-wise.
invert(x, /[, out, where, casting, order, …])|Compute bit-wise inversion, or bit-wise NOT, element-wise.
left_shift(x1, x2, /[, out, where, casting, …])|Shift the bits of an integer to the left.
right_shift(x1, x2, /[, out, where, …])|Shift the bits of an integer to the right.

### Funções de Comparação:

|Função|Descrição
|---|---|
greater(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 > x2) element-wise.
greater_equal(x1, x2, /[, out, where, …])|Return the truth value of (x1 >= x2) element-wise.
less(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 < x2) element-wise.
less_equal(x1, x2, /[, out, where, casting, …])|Return the truth value of (x1 =< x2) element-wise.
not_equal(x1, x2, /[, out, where, casting, …])|Return (x1 != x2) element-wise.
equal(x1, x2, /[, out, where, casting, …])|Return (x1 == x2) element-wise.
logical_and(x1, x2, /[, out, where, …])|Compute the truth value of x1 AND x2 element-wise.
logical_or(x1, x2, /[, out, where, casting, …])|Compute the truth value of x1 OR x2 element-wise.
logical_xor(x1, x2, /[, out, where, …])|Compute the truth value of x1 XOR x2, element-wise.
logical_not(x, /[, out, where, casting, …])|Compute the truth value of NOT x element-wise.
maximum(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.
minimum(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.
fmax(x1, x2, /[, out, where, casting, …])|Element-wise maximum of array elements.
fmin(x1, x2, /[, out, where, casting, …])|Element-wise minimum of array elements.

### Funções de Ponto Flutuante:

|Função|Descrição
|---|---|
isfinite(x, /[, out, where, casting, order, …])|Test element-wise for finiteness (not infinity or not Not a Number).
isinf(x, /[, out, where, casting, order, …])|Test element-wise for positive or negative infinity.
isnan(x, /[, out, where, casting, order, …])|Test element-wise for NaN and return result as a boolean array.
isnat(x, /[, out, where, casting, order, …])|Test element-wise for NaT (not a time) and return result as a boolean array.
fabs(x, /[, out, where, casting, order, …])|Compute the absolute values element-wise.
signbit(x, /[, out, where, casting, order, …])|Returns element-wise True where signbit is set (less than zero).
copysign(x1, x2, /[, out, where, casting, …])|Change the sign of x1 to that of x2, element-wise.
nextafter(x1, x2, /[, out, where, casting, …])|Return the next floating-point value after x1 towards x2, element-wise.
spacing(x, /[, out, where, casting, order, …])|Return the distance between x and the nearest adjacent number.
modf(x[, out1, out2], / [[, out, where, …])|Return the fractional and integral parts of an array, element-wise.
ldexp(x1, x2, /[, out, where, casting, …])|Returns x1 * 2**x2, element-wise.
frexp(x[, out1, out2], / [[, out, where, …])|Decompose the elements of x into mantissa and twos exponent.
fmod(x1, x2, /[, out, where, casting, …])|Return the element-wise remainder of division.
floor(x, /[, out, where, casting, order, …])|Return the floor of the input, element-wise.
ceil(x, /[, out, where, casting, order, …])|Return the ceiling of the input, element-wise.
trunc(x, /[, out, where, casting, order, …])|Return the truncated value of the input, element-wise.



## Operações Matemáticas com escalares

Operações com números escalares são possíveis de serem aplicadas à todos os elementos de um NumPy Array

In [146]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [148]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [152]:
arr = np.arange(1, 10).reshape(3, 3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
arr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [157]:
arr[1] = arr[1] * 2
arr

array([[ 1,  2,  3],
       [16, 20, 24],
       [ 7,  8,  9]])

## Operações entre arrays com a mesma forma e número de elementos

In [158]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [159]:
b = np.array([[5, 6], [7, 8]])
b

array([[5, 6],
       [7, 8]])

In [160]:
a * b

array([[ 5, 12],
       [21, 32]])

## Operações entre arrays com a mesma formas diferentes
Nesta situação a NumPy utiliza-se de um termo denominado difusão (broadcasting), onde o array menor é difundido ao array maior

In [161]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [163]:
b = np.array([5, 6])
b

array([5, 6])

In [164]:
a - b

array([[-4, -4],
       [-2, -2]])

In [165]:
b - a

array([[4, 4],
       [2, 2]])

## Slicing (Fatiamento)
Todos os elementos de um array, assim como outros tipos de listas do Python podem ser acessados diretamente pelo seu índice

In [168]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [169]:
a[0], a[2], a[-1]

(0, 2, 9)

Arrays multidimensionais, os índices são tuplas de inteiros

In [258]:
a = np.diag(np.arange(5))
a

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [250]:
a[1, 2]

0

In [257]:
a[2, 2]

99

In [259]:
a[2, 2] = 99

In [260]:
a

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0,  0, 99,  0,  0],
       [ 0,  0,  0,  3,  0],
       [ 0,  0,  0,  0,  4]])

O formato de _**slicing**_ do NumPy Array segue o padrão:

```javascript
A[start:end:step] 
```

para cada dimensão. Operações de slicing são muito eficientes para se extrair porções de um array

O formato de _**slicing**_ do NumPy Array segue o padrão:

```javascript
A[start:end:step] 
```

para cada dimensão. Operações de slicing são muito eficientes para se extrair porções de um array

In [261]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [262]:
arr[0,3:5]

array([3, 4])

In [263]:
arr[4:,4:]

array([[44, 45],
       [54, 55]])

In [264]:
arr[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [265]:
arr[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## Seleção condicional

In [221]:
arr = np.array([[ 0,  1,  2,  3,  4,  5],
                [10, 11, 12, 13, 14, 15],
                [20, 21, 22, 23, 24, 25],
                [30, 31, 32, 33, 34, 35],
                [40, 41, 42, 43, 44, 45],
                [50, 51, 52, 53, 54, 55]])
arr

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [228]:
mask = (arr % 2) == 0
mask

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [229]:
arr[mask]

array([ 0,  2,  4, 10, 12, 14, 20, 22, 24, 30, 32, 34, 40, 42, 44, 50, 52,
       54])

In [235]:
mask1 = (arr % 10) == 0
mask2 = (arr % 25) == 0
arr[(mask1 & mask2)]

array([ 0, 50])

In [236]:
arr[(mask1 | mask2)]

array([ 0, 10, 20, 25, 30, 40, 50])

In [238]:
mask3 = arr != 25

In [241]:
arr[((mask1 | mask2) & mask3)]

array([ 0, 10, 20, 30, 40, 50])

In [242]:
arr[np.where(np.logical_and(arr > 10, arr < 50))]

array([11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25, 30, 31, 32, 33, 34, 35,
       40, 41, 42, 43, 44, 45])

In [243]:
arr[np.where(np.logical_not(arr == 10))]

array([ 0,  1,  2,  3,  4,  5, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25,
       30, 31, 32, 33, 34, 35, 40, 41, 42, 43, 44, 45, 50, 51, 52, 53, 54,
       55])